import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ShieldCheck,Languages,FolderOpen,Upload,Play,Copy,Download,Undo2,RefreshCw,Network,Bug,Braces,FileCode2,XCircle,CheckCircle2,Plus,Trash2,Sparkles,ShieldAlert} from 'lucide-react';
import {createDownloadName,detectFileType,LIMITS,MATCH_MODES,parsePatchBlocks,sizeInfo} from './patchEngine';
import {LANGUAGES,getLanguage,getStrings,isRTL,setLanguage} from './i18n';
import {analyzeCodeIntelligence,analyzeProject} from './analysisEngine';
import {compilerHealth, patchWithCompilerServer, applyProjectWithServer, commitProjectWithServer} from './compilerClient';
import {AI_PROMPT} from './aiPrompt';
const C={bg:'#0b1020',card:'#121a2b',card2:'#0f1728',border:'#26324a',text:'#eef2ff',sub:'#9aa8c7',gold:'#d9b44a',green:'#37d67a',red:'#ff5d6c',blue:'#65a9ff',orange:'#ffb454'};
const box={background:C.card,border:`1px solid ${C.border}`,borderRadius:16,padding:16};
const mono={width:'100%',minHeight:280,resize:'vertical',background:'#080d18',color:'#e6edf7',border:`1px solid ${C.border}`,borderRadius:12,padding:14,fontFamily:'ui-monospace,SFMono-Regular,Menlo,Consolas,monospace',fontSize:13,lineHeight:1.55,direction:'ltr',textAlign:'left',outline:'none'};
const FILE_OPTIONS=[['auto','Auto'],['javascript','JavaScript'],['typescript','TypeScript'],['jsx','JSX'],['tsx','TSX'],['python','Python'],['java','Java'],['c','C'],['cpp','C++'],['go','Go'],['json','JSON'],['html','HTML'],['css','CSS'],['text','Text']];
export default function CodePatcher(){
 const compilerServerUrl=import.meta.env.VITE_COMPILER_SERVER_URL || 'http://127.0.0.1:8787';
 const compilerTypes=new Set(['java','c','cpp','go']);
 const [compilerOnline,setCompilerOnline]=useState(false);
 const [language,setUiLanguage]=useState(getLanguage());const t=getStrings(language),rtl=isRTL(language);const [view,setView]=useState('editor');
 const [files,setFiles]=useState([{fileName:'source.js',content:'',patchText:''}]);const [active,setActive]=useState(0);const f=files[active]||files[0];
 const [result,setResult]=useState(''),[status,setStatus]=useState(null),[audit,setAudit]=useState(null),[analysis,setAnalysis]=useState(null),[projectAnalysis,setProjectAnalysis]=useState(null),[projectResult,setProjectResult]=useState(null),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false),[history,setHistory]=useState([]);const inputRef=useRef();
 const [aiPromptCopied,setAiPromptCopied]=useState(false);
 const [serverProjectTx,setServerProjectTx]=useState(null);
 const projectPathsReady=files.length>0 && files.every(x=>String(x.filePath||'').trim().length>0);
 const [reviewApproved,setReviewApproved]=useState(false);
 const copyAiPrompt=async()=>{await navigator.clipboard?.writeText(AI_PROMPT);setAiPromptCopied(true);setTimeout(()=>setAiPromptCopied(false),1500)};
 const parsed=useMemo(()=>parsePatchBlocks(f.patchText),[f.patchText]);
 useEffect(()=>{document.documentElement.lang=language;document.documentElement.dir=rtl?'rtl':'ltr'; compilerHealth(compilerServerUrl).then(x=>setCompilerOnline(x.ok===true));},[language,rtl,compilerServerUrl]);
 const update=(key,val)=>{setFiles(x=>x.map((a,i)=>i===active?{...a,[key]:val}:a));setReviewApproved(false)};
 const addFile=()=>{const name=`file-${files.length+1}.js`;setFiles([...files,{fileName:name,filePath:'',content:'',patchText:''}]);setActive(files.length);setView('editor');};
 const removeFile=()=>{if(files.length===1)return;const next=files.filter((_,i)=>i!==active);setFiles(next);setActive(Math.max(0,active-1));};
 const run=async()=>{if(!f.content)return setStatus({ok:false,message:t.emptyCode});if(!f.patchText.trim()||parsed.errors.length||!parsed.blocks.length)return setStatus({ok:false,message:t.invalidPatch});setBusy(true);setStatus({ok:true,message:t.tx});try{
   const fileType=detectFileType(f.fileName);
   let data;
   if(compilerTypes.has(fileType)){
     if(!compilerOnline){setStatus({ok:false,message:t.compilerServerOffline});setBusy(false);return;}
     data=await patchWithCompilerServer({id:`v15-${Date.now()}`,original:f.content,patchText:f.patchText,fileName:f.fileName,fileType,mode:MATCH_MODES.EXACT_UNIQUE,allowReviewApply:false,reviewApproved},{baseUrl:compilerServerUrl});
   } else {
     data=await new Promise((resolve,reject)=>{const w=new Worker(new URL('./patchWorker.js',import.meta.url),{type:'module'});const id=`v15-${Date.now()}`;w.onmessage=e=>{if(e.data.id===id){w.terminate();resolve(e.data)}};w.onerror=e=>{w.terminate();reject(e)};w.postMessage({id,original:f.content,patchText:f.patchText,fileName:f.fileName,fileType,mode:MATCH_MODES.EXACT_UNIQUE,allowReviewApply:false})});
   }
   if(data.ok && data.prepared){setHistory(h=>[...h,{fileIndex:active,content:f.content,resultBefore:result,approved:data.code}].slice(-20));setFiles(fs=>fs.map((x,i)=>i===active?{...x,content:data.code}:x));setResult(data.code);setAudit(data.audit||null);setAnalysis(analyzeCodeIntelligence(f.fileName,data.code));setStatus({ok:true,message:compilerTypes.has(fileType)?'V23: Server Compiler + Patch Core + AST + Security + Integrity gates passed.':'V23: Patch Core + AST + Security + Integrity gates passed.'})}else{setResult(f.content);setAudit(data.audit||null);setAnalysis(null);setStatus({ok:false,message:data.message||'Transaction rejected and rolled back.'})}
 }catch(e){setStatus({ok:false,message:e.message||'Execution failure'})}finally{setBusy(false)}};
 const analyze=()=>{const a=analyzeCodeIntelligence(f.fileName,result||f.content);setAnalysis(a);setView('analysis');};
 const projectAnalyze=()=>{setProjectAnalysis(analyzeProject(files));setView('project')};
 const applyProject=async()=>{setBusy(true);try{const before=files.map(x=>({...x}));const r=await applyProjectWithServer(files.map(x=>({...x,filePath:x.filePath||''})),{baseUrl:compilerServerUrl,mode:MATCH_MODES.EXACT_UNIQUE,reviewApproved});setProjectResult(r);if(r.ok){setServerProjectTx(r);setHistory(h=>[...h,{kind:'project',filesBefore:before}].slice(-20));setFiles(fs=>fs.map((x,i)=>({...x,content:r.results[i]?.code??x.content})));setActive(0);setResult(r.results[0]?.code??'');setReviewApproved(false);}}catch(e){setProjectResult({ok:false,message:e?.message||'Project server error.'})}finally{setBusy(false)}};
 const commitProject=async()=>{if(!serverProjectTx?.transactionId)return;setBusy(true);try{const r=await commitProjectWithServer(serverProjectTx.transactionId,{baseUrl:compilerServerUrl});setProjectResult(r);if(r.ok)setServerProjectTx(null);}catch(e){setProjectResult({ok:false,message:e?.message||'Project commit error.'})}finally{setBusy(false)}};
 const copy=async()=>{await navigator.clipboard?.writeText(result);setCopied(true);setTimeout(()=>setCopied(false),1500)};
 const download=()=>{if(!result)return;const a=document.createElement('a'),u=URL.createObjectURL(new Blob([result],{type:'text/plain'}));a.href=u;a.download=createDownloadName(f.fileName);a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};
 const undo=()=>{const h=history[history.length-1];if(!h)return;if(h.kind==='project'){setFiles(h.filesBefore);setActive(0);setResult(h.filesBefore[0]?.content||'');}else{setActive(h.fileIndex??active);setFiles(fs=>fs.map((x,i)=>i===(h.fileIndex??active)?{...x,content:h.content}:x));setResult(h.resultBefore||h.content);}setHistory(history.slice(0,-1))};
 return <main style={{minHeight:'100vh',background:C.bg,color:C.text,fontFamily:'system-ui,sans-serif',padding:18,direction:rtl?'rtl':'ltr'}}><div style={{maxWidth:1400,margin:'auto'}}>
  <header style={{...box,display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap',marginBottom:16}}><div style={{display:'flex',gap:12,alignItems:'center'}}><ShieldCheck color={C.green} size={32}/><div><h1 style={{margin:0,fontSize:21}}>Code Patcher V23 Core-First</h1><div style={{color:C.sub,fontSize:12}}>Atomic Patch Core • Real AST • Compiler Server • Cross-file Impact • Security • Rollback</div></div></div><div style={{display:'flex',gap:7,flexWrap:'wrap',alignItems:'center'}}><label style={btn(false)}><Languages size={15}/><select value={language} onChange={e=>{setLanguage(e.target.value);setUiLanguage(e.target.value)}} style={sel}>{LANGUAGES.map(([c,n])=><option key={c} value={c}>{n}</option>)}</select></label><button style={btn(view==='editor')} onClick={()=>setView('editor')}><Braces size={15}/>IDE</button><button style={btn(view==='analysis')} onClick={analyze}><Bug size={15}/>Analysis</button><button style={btn(view==='project')} onClick={projectAnalyze}><Network size={15}/>{t.projectGraph}</button><span style={{...metric,padding:'7px 9px'}}>{compilerOnline?t.compilerServerOn:t.compilerServerOff}</span><span style={{...metric,padding:'7px 9px'}}>V23 Safety Gates: Parse • Verify • Security • Integrity • Impact</span><button onClick={copyAiPrompt} style={btn(false)} title="ينسخ برومت جاهز يشرح تنسيق الأداة لأي برنامج ذكاء اصطناعي">{aiPromptCopied ? <CheckCircle2 size={15}/> : <Sparkles size={15}/>} {aiPromptCopied ? t.aiPromptCopied : t.aiPromptButton}</button><button style={btn(false)} onClick={undo} disabled={!history.length}><Undo2 size={15}/>{t.undo}</button><button style={btn(false)} onClick={()=>{setFiles([{fileName:'source.js',filePath:'',content:'',patchText:''}]);setActive(0);setResult('');setStatus(null);setAnalysis(null);setReviewApproved(false)}}><RefreshCw size={15}/>{t.reset}</button></div></header>
  <section style={{...box,marginBottom:12,display:'flex',gap:7,alignItems:'center',overflowX:'auto'}}>{files.map((x,i)=><button key={i} onClick={()=>{setActive(i);setView('editor')}} style={{...btn(i!==active),whiteSpace:'nowrap'}}><FileCode2 size={14}/>{x.fileName}</button>)}<button style={btn(false)} onClick={addFile}><Plus size={15}/>{t.addFiles||'Add file'}</button>{files.length>1&&<button style={btn(false)} onClick={removeFile}><Trash2 size={15}/></button>}</section>
  {view==='editor'&&<><section style={{...box,marginBottom:12,display:'grid',gridTemplateColumns:'2fr 1fr 1fr',gap:10}}><label>File name<input value={f.fileName} onChange={e=>update('fileName',e.target.value)} style={input}/></label><label>Workspace path (project commit)<input value={f.filePath||''} onChange={e=>update('filePath',e.target.value)} style={input}/></label><label>Type<select value={detectFileType(f.fileName)} onChange={e=>update('fileName',f.fileName.replace(/\.[^.]+$/,'')+'.'+({javascript:'js',typescript:'ts',python:'py',java:'java',c:'c',cpp:'cpp',go:'go',json:'json',html:'html',css:'css'}[e.target.value]||'txt'))} style={input}>{FILE_OPTIONS.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Chars<div style={metric}>{sizeInfo(f.content).chars.toLocaleString()} / {LIMITS.maxSourceChars.toLocaleString()}</div></label></section>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(350px,1fr))',gap:12}}><section style={box}><h3>Original / Editor</h3><textarea value={f.content} onChange={e=>{update('content',e.target.value);setResult('')}} style={mono}/><input ref={inputRef} hidden type="file" onChange={e=>{const file=e.target.files?.[0];if(file){file.text().then(s=>{update('content',s);update('fileName',file.name)})}}}/><button style={btn(false)} onClick={()=>inputRef.current?.click()}><Upload size={15}/>Upload</button></section><section style={box}><h3>SEARCH / REPLACE Patch</h3><textarea value={f.patchText} onChange={e=>update('patchText',e.target.value)} style={mono}/><div style={metric}>Blocks: {parsed.blocks.length} • Errors: {parsed.errors.length}</div></section></div>
  <div style={{display:'flex',gap:8,margin:'12px 0',alignItems:'center',flexWrap:'wrap'}}><button disabled={busy} onClick={run} style={{...btn(busy),flex:1,background:busy?'#1a2234':C.gold,color:'#111',border:0,padding:14}}><Play size={17}/>{busy?'Running…':t.run}</button><label style={{display:'flex',alignItems:'center',gap:6,fontSize:12,color:C.sub}} title={t.reviewApprovedHint}><input type="checkbox" checked={reviewApproved} onChange={e=>setReviewApproved(e.target.checked)}/><ShieldAlert size={14}/>{t.reviewApprovedLabel}</label></div></>}
  {view==='analysis'&&<AnalysisPanel analysis={analysis} t={t}/>} 
  {view==='project'&&<section style={box}><h2><Network size={19}/> {t.projectGraph}</h2>{projectAnalysis&&<><div style={cards}><Metric n={t.filesMetric} v={projectAnalysis.summary.files}/><Metric n={t.diagnosticsMetric} v={projectAnalysis.summary.diagnostics}/><Metric n={t.taintMetric} v={projectAnalysis.summary.taintFlows}/><Metric n={t.cyclesMetric} v={projectAnalysis.summary.cycles}/></div><pre style={pre}>{JSON.stringify(projectAnalysis.graph,null,2)}</pre><div>{projectAnalysis.analyses.map((a,i)=><div key={i} style={row(a.typeCheck.ok&&a.taint.findings.length===0?C.green:C.red)}><b>{a.fileName}</b> — {a.typeCheck.diagnostics.length} diagnostics • {a.taint.findings.length} taint flows</div>)}</div><div style={{marginTop:8,color:C.sub,fontSize:12}}>{t.intelligenceNote}</div></>}{!projectAnalysis&&<button onClick={projectAnalyze} style={btn(false)}>{t.analyzeProject}</button>}<div style={{display:'flex',gap:8,marginTop:10,alignItems:'center',flexWrap:'wrap'}}><button disabled={busy||!compilerOnline||!projectPathsReady} onClick={applyProject} style={{...btn(false),background:C.blue,color:'#08111f',border:0}}><FolderOpen size={15}/>Prepare project transaction</button>{serverProjectTx?.transactionId&&<button disabled={busy} onClick={commitProject} style={{...btn(false),background:C.green,color:'#08111f',border:0}}><CheckCircle2 size={15}/>Commit prepared project</button>}<label style={{display:'flex',alignItems:'center',gap:6,fontSize:12,color:C.sub}} title={t.reviewApprovedHint}><input type="checkbox" checked={reviewApproved} onChange={e=>setReviewApproved(e.target.checked)}/><ShieldAlert size={14}/>{t.reviewApprovedLabel}</label></div>{projectResult&&<div style={row(projectResult.ok?C.green:C.red)}>{projectResult.message}</div>}</section>}
  {status&&<section style={{...box,marginTop:12,borderColor:status.ok?C.green:C.red}}>{status.ok?<CheckCircle2 color={C.green}/>:<XCircle color={C.red}/>} {status.message}</section>}
  {result&&<section style={{...box,marginTop:12}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><h2>Approved Result</h2><div><button style={btn(false)} onClick={copy}><Copy size={14}/>{copied?'Copied':t.copy}</button><button style={btn(false)} onClick={download}><Download size={14}/>{t.download}</button></div></div><textarea readOnly value={result} style={{...mono,minHeight:350}}/>{audit&&<pre style={pre}>{JSON.stringify(audit,null,2)}</pre>}</section>}
 </div></main>
}
function AnalysisPanel({analysis,t}){if(!analysis)return <section style={box}><Bug/> Run analysis after a file is loaded.</section>;return <section style={box}><h2><Bug/> Static Intelligence</h2><div style={cards}><Metric n="Type diagnostics" v={analysis.typeCheck.diagnostics.length}/><Metric n="Taint sources" v={analysis.taint.sources}/><Metric n="Taint sinks" v={analysis.taint.sinks}/><Metric n="Taint flows" v={analysis.taint.findings.length}/></div><h3>Type / consistency diagnostics</h3>{analysis.typeCheck.diagnostics.map((d,i)=><div key={i} style={row(d.severity==='error'?C.red:C.orange)}>{d.code} — line {d.line}: {d.message}</div>)}{analysis.typeCheck.diagnostics.length===0&&<div style={row(C.green)}>No static type/consistency diagnostics.</div>}<h3>Data-flow / taint</h3>{analysis.taint.findings.map((d,i)=><div key={i} style={row(C.red)}>{d.code} — source {d.sourceLine} → sink {d.sinkLine}: {d.message}</div>)}{analysis.taint.findings.length===0&&<div style={row(C.green)}>No source-to-sink flow detected by current rules.</div>}<div style={{marginTop:12,color:C.sub,fontSize:12}}>{t?.intelligenceNote||'These are static analysis gates; user code is never executed.'}</div></section>}
const cards={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:8,margin:'10px 0'};const pre={background:'#080d18',padding:12,borderRadius:10,overflow:'auto',fontSize:11,direction:'ltr',textAlign:'left'};const metric={padding:9,background:C.card2,borderRadius:9,color:C.sub};function Metric({n,v}){return <div style={metric}><b>{n}</b><br/><strong style={{fontSize:20,color:C.text}}>{v}</strong></div>}function btn(dis){return{display:'inline-flex',alignItems:'center',gap:6,padding:'9px 11px',borderRadius:9,border:`1px solid ${C.border}`,background:dis?'#151f33':'#151f33',color:dis?'#77829a':C.text,cursor:dis?'not-allowed':'pointer',fontWeight:800,fontSize:12}}const input={display:'block',width:'100%',marginTop:6,padding:9,borderRadius:8,background:'#080d18',color:C.text,border:`1px solid ${C.border}`};const sel={background:'#080d18',color:C.text,border:0,outline:0};function row(color){return{display:'flex',gap:8,padding:9,margin:'6px 0',background:C.card2,border:`1px solid ${C.border}`,borderRadius:9,color,fontSize:12}}
